### ISSUE TITLE
Footer 하단 고정 문제

### ISSUE THREAD

**Issue by Dawon00** [Dawon00/momo-project#5]
![image](https://user-images.githubusercontent.com/71630722/186409271-644fc643-1e60-447d-88dc-fbd0e379c933.png)

Detail page 작업 도중
Footer 이미지가 하단에 고정되지 않는 문제가 발생했습니다.
페이지의 content가 많아져서 스크롤을 아래로 내리더라도 footer가 화면 중간에 보이지 않도록 수정되어야 합니다.

**Comment by juhui88** [comment]
position absolute로 인한 문제로 수정완료하였습니다
혹시 footer가 맨 밑에 안 내려가면 전체 감싸져있는 요소를 min-height:100vh; 으로 설정하길 바랍니다.
